Tong/wk08/4-thu/hogwarts-master/config/routes.rb
Rails.application.routes.draw do

  root "houses#index"
  resources :houses, only: [:index, :show]
  resources :students, only: [:index, :show,:new]

end

Tong/wk08/4-thu/hogwarts-master/app/models/house.rb
class House < ActiveRecord::Base
    has_many :students
    
end

Tong/wk08/4-thu/hogwarts-master/app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :house
end

Tong/wk08/4-thu/hogwarts-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Tong/wk08/4-thu/hogwarts-master/app/controllers/houses_controller.rb
class HousesController < ApplicationController

  def index
    @houses = House.all
  end

  def show
    @houses = House.all
    @house = House.find(params[:id])
  end

end

Tong/wk08/4-thu/hogwarts-master/app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

end

Tong/wk08/4-thu/hogwarts-master/app/views/houses/index.html.erb
<h1>The houses</h1>
<% @houses.each do |house| %>
  <div class="house">
    <h2><a href="/houses/<%=house.id%>"><%=house.name%></a></h2>
    <img src="<%= house.img_url %>"/>
  </div>
<% end %>

Tong/wk08/4-thu/hogwarts-master/app/views/houses/show.html.erb
<h1><%= @house.name %></h1>
<% @house.students.each do |student| %>
  <div class="student">
    <h2><%= student.name %></h2>
    <%= image_tag student.img_url %>
  </div>
<% end %>

Tong/wk08/4-thu/hogwarts-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <title>Hogwarts</title>
  </head>
  <body>
    <nav>
      <h1>Welcome to Hogwarts!</h1>
      <h2><%= link_to "View Houses", houses_path %> | <%= link_to "View Students", students_path %> | <%= link_to "Enroll", student_path("new") %></h2>
    </nav>

    <%= yield %>

  </body>
</html>

Tong/wk08/4-thu/hogwarts-master/app/views/students/index.html.erb
<h1>Here are the students</h1>
<% @students.each do |student| %>
  <div>
    <%= link_to student.name, student_path(student) %> - <%= student.house.name %>
     </div>
<% end %>
 

Tong/wk08/4-thu/hogwarts-master/app/views/students/new.html.erb
<h1>Welcome to the Sorting Hat!</h1>
<%= image_tag "http://flavorwire.files.wordpress.com/2009/06/sorting-hat.jpg" %>

<div class="eroll-info">
    <form action="">
        <label for="">Your name</label>
        <input type="text" class ="name">
        <button>submit</button>
    </form>
</div>

Tong/wk08/4-thu/hogwarts-master/app/views/students/show.html.erb
<h1><%= @student.name %></h1>
<h2><%= @student.house.name %></h2>
<div class="student">
  <%= image_tag @student.img_url %>
</div>